version: "3"

services:
  remio-home:
    # image: kasuie/remio-home
    image: registry.cn-shanghai.aliyuncs.com/remio/remio-home
    container_name: remio-home
    ports:
      - "3000:3000"
    # environment:
    #   - TZ=Asia/Shanghai
    #   - GTMID=value # Google Tag Manager
    #   - GTAGID=value # Google Analytics
    #   - BAIDUID=value # 百度统计
    env_file:
      - .env
    volumes:
      # - /usr/local/config:/remio-home/config
      # - /usr/local/icons:/remio-home/public/icons

      - ./src/config:/remio-home/config
      - ./public/icons:/remio-home/public/icons
      - ./public/fonts:/remio-home/public/fonts
    restart: unless-stopped